name: story_app
description: "Story App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  flutter_smart_dialog: ^4.9.6
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  logger: ^2.0.2+1
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  infinite_scroll_pagination: ^4.0.0
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.0
  skeletonizer: ^1.0.1
  cached_network_image: ^3.3.1
  intl: ^0.18.1
  flutter_expandable_fab: ^2.0.0
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/


